### ISSUE TITLE
无法成功加载so

### ISSUE THREAD

**Issue by yubazi** [asLody/whale#15]
报错信息
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.mycompany.myapp2-DLOtD7x501pU-Ny_bXg98w==/lib/arm64/libwhale.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1669)
	at com.lody.whale.WhaleRuntime.<clinit>(WhaleRuntime.java:19)
	at com.lody.whale.WhaleRuntime.hookMethodNative(Native Method)
	at com.lody.whale.xposed.XposedBridge.hookMethod(XposedBridge.java:100)
	at com.lody.whale.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
	at com.mycompany.myapp2.MainActivity.onCreate(MainActivity.java:16)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1838)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6835)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by yubazi** [comment]
两个libart.so
链接:https://pan.baidu.com/s/1sRnPloNADMh54xB4r9gQwA 提取码:5q52 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by haoshaolin** [comment]
同样的错，怎么解决的？

**Comment by NoahNyy** [comment]
+1
