### ISSUE TITLE
编译通过,但是运行时报错

### ISSUE THREAD

**Issue by wjy000** [asLody/whale#3]
Android Studio 3.3.1
===========LOG===========
2019-02-12 15:15:44.125 30569-30569/? E/Whale: Unable to read data from libart.so.
2019-02-12 15:15:44.125 30569-30569/? E/Whale: Runtime setup failed

===========异常===========
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ting, PID: 29789
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.ting-wjPnF8gWMDr42MYlTbSJEQ==/lib/arm64/libwhale.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.ting.MainActivity.<clinit>(MainActivity.java:13)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6685)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by asLody** [comment]
已修复，可以测试一下了.

**Comment by WaterlooBridge** [comment]
将sscanf的format参数改为"%x-%x %s %x %s %d %s"之后，依旧不行，取出perm仍然是空的
LOG(ERROR) << buf;
LOG(ERROR) << begin << " " << end << " " << perm << " " << foo << " " << dev << " " << inode << " " << mapname;
打印结果：
2019-02-13 16:10:08.338 19518-19518/? E/Whale: ef008000-ef434000 r-xp 00000000 103:04 2110                              /system/lib/libart.so
2019-02-13 16:10:08.338 19518-19518/? E/Whale: 4009787392 4014161920  0 103:04 2110 /system/lib/libart.so
2019-02-13 16:10:08.338 19518-19518/? E/Whale: ef434000-ef43c000 r--p 0042b000 103:04 2110                              /system/lib/libart.so
2019-02-13 16:10:08.338 19518-19518/? E/Whale: 4014161920 4014194688  4370432 103:04 2110 /system/lib/libart.so
2019-02-13 16:10:08.338 19518-19518/? E/Whale: ef43c000-ef43e000 rw-p 00433000 103:04 2110                              /system/lib/libart.so
2019-02-13 16:10:08.338 19518-19518/? E/Whale: 4014194688 4014202880  4403200 103:04 2110 /system/lib/libart.so

**Comment by asLody** [comment]
@WaterlooBridge 64bit不走这里， 走的是#if defined(__LP64__)。
你提供的 `ef008000-ef434000 r-xp 00000000 103:04 2110 /system/lib/libart.so`
使用参数: `%lx-%lx %s %lx %s %ld %s`是可以正常运行的。

**Comment by asLody** [comment]
@WaterlooBridge 现在应该可以了

**Comment by WaterlooBridge** [comment]
@asLody Thank you，可以了
