### ISSUE TITLE
crash apps

### ISSUE THREAD

**Issue by wormfake** [asLody/whale#48]
1574695699.873 5437-5437/com.comacdb E/Whale: Unable to read data from libart.so.
1574695699.873 5437-5437/comacdb  E/Whale: Runtime setup failed
1574695699.879 5437-5437/comacdbE/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dn.habadu, PID: 5437
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/comacdb-BAvmWM1IArBrqemtkQWygw==/lib/arm64/libwhale.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.lody.whale.WhaleRuntime.<clinit>(WhaleRuntime.java:19)
        at com.lody.whale.WhaleRuntime.hookMethodNative(Native Method)
        at com.lody.whale.xposed.XposedBridge.hookMethod(XposedBridge.java:103)
        at com.dn.habadu.activity.MainA.hook_methods(MainA.java:100)
        at com.dn.habadu.activity.MainA.executeHook(MainA.java:110)
        at com.dn.habadu.activity.MainA.onCreate(MainA.java:71)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kiwi-bo** [comment]
in android Q?
libart.so is move to /apex/com.android.runtime/lib/libart.so in android Q

**Comment by 850636558myj** [comment]
android 10   必崩溃，可以自测适配看看，

**Comment by kiwi-bo** [comment]
android 10是因为符号查找失败导致的，我已经适配了，目前尚未解决的问题是，hook 自定义的函数没问题，但是hook系统函数，会出现release必定崩溃，调试模式下正常
